import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    grade_crop: 'Grade Crop',
    market_prices: 'Market Prices',
    sale_advisor: 'Sale Advisor',
    pooling: 'Pooling',
    my_products: 'My Products',
    settlement: 'Settlement',
    logout: 'Logout',
    start_selling: 'Start Selling',

    // Top Bar
    voice: 'Voice',
    online: 'Online',
    offline: 'Offline',
    location_grid: 'Baramati Cluster, Pune | Live APMC Grid: Pune Cluster',
    national_portal: 'National Agriculture Portal (Live)',

    // Greetings & Headers
    greeting: 'Namaste',
    online_status_line: 'Online • Real-Time Pune APMC Connected • Live Market Feed Active',
    offline_status_line: 'Offline Mode • Local Queue Active • Cached Mandi Rates',
    current_farm_location: 'Current Farm Location',
    accuracy_manual: 'Accuracy: Manual (Taluka/District)',
    change_location: 'Change Location',

    // KPI Cards
    todays_best_net: "Today's Best Net",
    current_crop_grade: 'Current Crop Grade',
    external_ai_estimate: 'External Visual AI Estimate',
    active_pool_progress: 'Active Pool Progress',
    pending_payment: 'Pending Payment',
    released_in_nodal: 'Released in Nodal Account',

    // Map & Journey
    mandi_map_title: 'Farm & Nearby Mandi Map',
    mandi_map_subtitle: 'Dynamic routes and travel times originating from Baramati Cluster, Pune',
    mandis_found: '22 Mandis Found',
    journey_title: 'END-TO-END MARKET LINKAGE JOURNEY',
    step1: '1. Capture 3 Photos',
    step2: '2. External AI Grade',
    step3: '3. Net Mandi Compare',
    step4: '4. FPO Group Pooling',
    step5: '5. Nodal Payout',

    recent_lots: 'Recent Lots',
    recent_lots_subtitle: 'Your active and verified crop lots in the system',
    your_harvest_produce_lots: 'Your Harvest Produce Lots',
    your_harvest_produce_lots_desc: 'Your active, graded, and verified harvest produce lots in the system',
    nearby_mandis: 'Nearby Mandis',
    near_baramati: 'Near Baramati Cluster',
    direct_buyer_offers: 'Direct Buyer Offers',
    direct_buyer_offers_subtitle: 'Verified buyers offering to buy your produce directly.',
    buyer_procurement: 'Buyer Procurement',
    buyer_procurement_subtitle: 'Verified corporate buyers procuring directly at official Mandi modal rates. Zero commission, direct escrow credit.',
    your_harvest_listings: 'Your Harvest Produce Lots',

    // Offline Banner
    offline_banner_title: 'You are offline. Crop drafts and pool requests are safely queued in your local browser and will sync automatically when back online.',
    offline_mode_badge: 'Offline Mode',
    offline_mode_desc: 'Simulated local storage queue is active. You can create lots and join pools; they will synchronize when connection is restored.',
    offline_bullet_1: 'Last saved location: Baramati Cluster, Pune',
    offline_bullet_2: 'Cached mandi rates available',
    offline_bullet_3: 'Live buyer offers and payments pause until back online',

    // AI Assistant
    ai_assistant_title: 'KrishiSetu AI Assistant',
    ai_welcome: 'Hello! I am your KrishiSetu AI Assistant. Ask me about nearby mandi prices, net transport outcomes, quality grading, or FPO pooling.',
    ai_input_placeholder: 'Type or speak your question...',
    ask_tomato: "What is today's tomato price near me?",
    ask_net: 'Which mandi gives me the best net return?',
    ask_fpo: 'How does FPO pooling work?',
    // Buyer Navigation & Subpages
    buyer_nav_marketplace: 'Marketplace',
    buyer_nav_offers: 'My Offers',
    buyer_nav_delivery: 'Delivery Acceptance',
    buyer_nav_trades: 'Trades & Settlements',

    // FPO Navigation
    fpo_nav_dashboard: 'Dashboard',
    fpo_nav_verify: 'Verify Lots',
    fpo_nav_pools: 'Pool Management',
    fpo_nav_logistics: 'Logistics',
    fpo_nav_buyers: 'Buyers',
    switch_portal: 'Switch Portal',

    // Buyer Marketplace
    b2b_marketplace_title: 'B2B Wholesale Agri Marketplace',
    b2b_marketplace_subtitle: 'Procure FPO-verified, escrow-protected aggregated consignments. Connected directly to farms.',
    rbi_compliant_escrow: 'RBI-Compliant Escrow',
    available_pools: 'Available Pools',
    total_stock: 'Total Stock',
    total_market_value: 'Total Market Value',
    registered_buyers: 'Registered Buyers',
    direct_farmer_lots: 'Direct Farmer Lots',
    aggregated_fpo_pools: 'Aggregated FPO Pools',
    filter_label: 'Filter:',
    clear_filter: 'Clear',
    view_product_details: 'View Product Details',
    reserve_pool: 'Reserve Pool',
    already_reserved: 'Already Reserved',
    fpo_inspected: 'FPO Inspected',
    fpo_certified: 'FPO Certified',
    available_volume: 'Available Volume',
    asking_rate: 'Asking Rate',
    producer_label: 'Producer:',
    ai_quality_score: 'AI Quality Score:',
    lot_id: 'Lot ID:',
    pool_fill_progress: 'Pool Fill Progress',
    freight_saved: 'Freight Saved',
    est_total_value: 'Est. Total Value:',
    auth_escrow_title: 'Authorize Nodal Escrow Hold',
    zero_advance_protection: 'Zero-Advance Escrow Protection',
    confirm_reserve: 'Confirm & Reserve',
    cancel: 'Cancel',

    // Buyer Orders & RFQs
    procurement_orders_title: 'Procurement Orders & RFQs',
    procurement_orders_subtitle: 'Publish direct purchase requirements to FPOs or track existing contracts.',
    broadcast_new_rfq: 'Broadcast New RFQ',
    target_ceiling_price: 'Target Ceiling Price',
    quality_tolerance: 'Quality Tolerance',
    total_procurement_commitment: 'Total Procurement Commitment',
    delivery_destination: 'Delivery Destination',
    fulfillment_progress: 'Fulfillment Progress',
    contributing_farmers: 'Contributing Farmers',
    fully_fulfilled: 'Fully Fulfilled ✓',
    remaining: 'remaining',
    min_supply_lot: 'Min supply lot',
    delivery_deadline: 'Delivery deadline',

    // Buyer Delivery
    delivery_acceptance_title: 'Delivery Acceptance & Payout Release',
    delivery_acceptance_subtitle: 'Inspect arrived consignments against digital weigh-slips. Release funds or log quality adjustments within 24 hours.',
    no_active_deliveries: 'You have no active deliveries. Reserve a pool in the B2B Marketplace first.',
    consignment: 'Consignment',
    consignment_value: 'Consignment Value:',
    assigned_fpo: 'Assigned FPO',
    verified_bulk_weight: 'Verified Bulk Weight',
    assigned_transporter: 'Assigned Transporter',
    contract_price: 'Contract Price',
    ondc_ready_logistics: 'ONDC Protocol Ready Logistics',
    vehicle_arrival_inspection: 'Vehicle Arrival & Quality Inspection',
    vehicle_arrival_desc: 'Scan the vehicle gate QR pass and match crates against the FPO digital weigh-slip before releasing the nodal escrow payment.',
    raise_dispute: 'Raise Quality/Weight Dispute',
    confirm_delivery: 'Confirm Delivery & Release Funds',
    delivery_accepted_payout: 'Delivery Accepted & Payment Released',
    dispute_raised_funds_held: 'Dispute Raised — Funds on Nodal Hold',
    my_procurement_bids: 'My Procurement Bids & Orders (FPO Linkage)',
    withdraw_bid: 'Withdraw Bid',

    // Buyer Trades
    trades_title: 'Auction Trades & Settlements',
    trades_subtitle: 'Double-auction cleared contracts, nodal escrow locks, clearing vouchers, and instant bank UTR settlement.',
    cleared_volume: 'Cleared Volume',
    total_settled: 'Total Settled',
    pending_escrow: 'Pending Escrow',
    clearing_ledger: 'Auction Clearing Ledger & Vouchers',
    pay_and_settle: 'Pay & Settle',
    settled_badge: 'Settled ✓',

    // FPO Portal Translations
    fpo_registered_badge: 'Registered FPO',
    fpo_lots_pending_btn: 'Lots Pending',
    fpo_verify_lots_btn: 'Verify Lots',
    fpo_kpi_pending: 'PENDING',
    fpo_kpi_pending_sub: 'Lots awaiting verification',
    fpo_kpi_verified: 'VERIFIED',
    fpo_kpi_verified_sub: 'Ready or Pooled',
    fpo_kpi_active_pools: 'ACTIVE POOLS',
    fpo_kpi_active_pools_sub: 'filled on avg',
    fpo_kpi_settled: 'SETTLED',
    fpo_kpi_settled_sub: 'Total escrow released',
    fpo_tab_overview: 'Overview',
    fpo_tab_lots: 'Lots',
    fpo_tab_pools: 'Pools',
    fpo_tab_logistics: 'Logistics',
    fpo_hub_map_title: 'FPO Hub & Nearby Mandi Map',
    fpo_hub_map_sub: 'Baramati, Pune — Live APMC satellite grid',
    fpo_lots_awaiting_title: 'Lots Awaiting Verification',
    fpo_view_all: 'View All',
    fpo_review_btn: 'Review',
    fpo_active_pools_title: 'Active Freight Pools',
    fpo_filled_pct: 'Filled',
    fpo_nearest_mandis_title: 'Nearest APMC Mandis',
    fpo_all_produce_lots: 'All Farmer Produce Lots',
    fpo_all_produce_lots_sub: 'Review, verify physical weigh-slips, or allocate lots into active freight pools.',
    fpo_weigh_slip_queue_btn: 'Physical Weigh-Slip Queue →',
    fpo_awaiting_inspection: 'Awaiting Inspection',
    fpo_inspect_btn: 'Inspect',
    fpo_active_regional_pools: 'Active Regional Freight Pools',
    fpo_create_manage_pools: '+ Create / Manage Pools',
    fpo_shared_freight_saved: 'Shared Freight Saved',
    fpo_manage_btn: 'Manage →',
    fpo_logistics_schedule_title: 'Logistics & Transport Schedule',
    fpo_logistics_schedule_sub: 'Multi-stop pickup routes and consignment weighbridge dispatches.',
    fpo_route_optimizer_btn: 'Open Route Optimizer →',
    fpo_assigned_fleet: 'Assigned Transport Fleet',
    fpo_current_loop: 'Current Multi-Stop Loop',
    fpo_full_utilization: 'Full Utilization',
    fpo_collective_fuel_savings: 'Collective Fuel Savings',
    fpo_cost_reduction: 'Cost Reduction',
    fpo_value_chain_title: 'FPO VALUE CHAIN: FARMER → MARKET → PAYMENT',
    fpo_step_lot_collection: 'Lot Collection',
    fpo_step_ai_verification: 'AI Quality Verification',
    fpo_step_pool_aggregation: 'Pool Aggregation',
    fpo_step_apmc_buyer: 'APMC / Buyer',
    fpo_step_escrow_settlement: 'Escrow Settlement',

    // FPO Physical Verification
    fpo_verify_page_title: 'Physical Lot Verification & Weigh-Slip',
    fpo_verify_page_sub: 'Review farmer-submitted AI estimates, enter certified weigh-bridge readings, and authorize pooling eligibility.',
    fpo_dual_grade_rule: 'Dual-Grade Accountability Rule: If farmer disputes FPO physical grade, a third-party APMC lab re-evaluates. 100% transparent audit trails logged on-chain.',
    fpo_awaiting_table_title: 'Lots Awaiting Physical Verification',
    fpo_hub_queue_sub: 'Baramati FPO Hub #1 incoming queue',
    fpo_col_farmer: 'Farmer',
    fpo_col_village: 'Village',
    fpo_col_crop: 'Crop / Variety',
    fpo_col_ai_grade: 'AI Grade Claimed',
    fpo_col_moisture: 'Moisture',
    fpo_col_status: 'Status',
    fpo_col_action: 'Action',
    fpo_inspect_weigh_btn: 'Inspect & Weigh',
    fpo_modal_inspect_title: 'Physical Inspection & Certified Weight',
    fpo_modal_lot_id: 'Lot ID',
    fpo_modal_farmer_name: 'Farmer Name',
    fpo_modal_crop_variety: 'Crop / Variety',
    fpo_modal_certified_weight: 'Certified Weigh-Bridge Net Weight (kg)',
    fpo_modal_physical_grade: 'Physical Grade Assignment',
    fpo_modal_grade_a: 'Grade A — Premium Export & Supermarket Quality',
    fpo_modal_grade_b: 'Grade B — Standard APMC Mandi Grade',
    fpo_modal_grade_c: 'Grade C — Industrial / Processing Grade',
    fpo_modal_moisture_reading: 'Dual Moisture Reading (%)',
    fpo_modal_inspector_notes: 'Inspector Observations & Quality Notes',
    fpo_modal_reject_btn: 'Reject & Return to Farmer',
    fpo_modal_confirm_btn: 'Confirm & Issue Weigh-Slip',

    // FPO Pool Management
    fpo_pools_page_title: 'Freight Pool Management',
    fpo_pools_page_sub: 'Aggregate verified farmer harvests into multi-farmer truckload lots to cut transport costs by up to 35%.',
    fpo_create_pool_btn: '+ Create New Batch Pool',
    fpo_target_capacity: 'Target Capacity',
    fpo_current_volume: 'Current Volume',
    fpo_target_price: 'Target Rate',
    fpo_allowed_grades: 'Allowed Grades',
    fpo_closes_in: 'Closes In',
    fpo_optimize_route_btn: 'Optimize Route',
    fpo_lock_pool_btn: 'Lock & Dispatch Pool',
    fpo_pool_locked_badge: 'Locked & Dispatched',
    fpo_contributing_farmers: 'Contributing Farmers',
    fpo_modal_create_pool_title: 'Launch New Regional Batch Pool',
    fpo_modal_crop_name: 'Crop Name',
    fpo_modal_variety: 'Variety',
    fpo_modal_target_weight_kg: 'Target Batch Weight (kg)',
    fpo_modal_target_price_qtl: 'Target Modal Price (₹/Quintal)',
    fpo_modal_dest_mandi: 'Destination Mandi / Buyer Hub',
    fpo_modal_collection_hub: 'FPO Collection Hub',
    fpo_modal_cutoff_hrs: 'Pool Cutoff Window (Hours)',
    fpo_modal_launch_btn: 'Launch Pool',

    // FPO Logistics
    fpo_logistics_page_title: 'Logistics & Route Optimization',
    fpo_logistics_page_sub: 'Google OR-Tools CVRPTW solver generates optimal farmer pickup sequences and bulk transport dispatches.',
    fpo_cost_reduction_badge: '28.5% Freight Cost Reduction vs Solo Vehicles',
    fpo_optimized_sequence: 'Optimized Multi-Stop Pickup Sequence',
    fpo_cvrptw_algo_sub: 'Algorithm: Capacitated Vehicle Routing Problem with Time Windows (CVRPTW)',
    fpo_vehicle_label: 'Vehicle',
    fpo_total_loop_dist: 'Total Loop Distance',
    fpo_driver_assigned: 'Driver Assigned',
    fpo_est_route_cost: 'Estimated Route Cost',
    fpo_farmer_savings: 'Collective Farmer Savings',
    fpo_scheduled_stops_title: 'SCHEDULED PICKUP TIMELINE & GEOLOCATION STOPS',
    fpo_stop_label: 'Stop',
    fpo_farmer_contact: 'Farmer Contact',
    fpo_pickup_weight: 'Pickup Weight',
    fpo_dispatch_btn: 'Authorize Multi-Stop Dispatch & Generate Transit Manifest',
    fpo_dispatched_badge: 'Consignment in Transit',

    // FPO Verified Buyers
    fpo_buyers_page_title: 'Verified B2B Buyers Directory',
    fpo_buyers_page_sub: 'Partnered institutional procurers, food retailers, and processing units with pre-verified payment records.',
    fpo_buyers_kyc_badge: 'All Buyers KYC & GSTIN Verified',
    fpo_reliability_score: 'Reliability Score',
    fpo_gstin_label: 'GSTIN',
    fpo_quality_req_label: 'Quality Requirement',
    fpo_payment_term_label: 'Payment Settlement Term',
    fpo_target_commodities: 'Target Commodities',
    fpo_historical_vol: 'Verified Historical Volume',
    fpo_contact_procurement_btn: 'Contact Procurement Desk',
    fpo_send_pool_offer_btn: 'Send Pool Offer',
    auction_listing: 'Auction Listing',
    live_apmc_grid: 'Live APMC Grid: Pune Cluster',
  },

  mr: {
    // Navigation
    dashboard: 'डॅशबोर्ड',
    grade_crop: 'पीक प्रतवारी (Grade)',
    market_prices: 'बाजार भाव',
    sale_advisor: 'विक्री सल्लागार',
    pooling: 'एफपीओ गट एकत्रीकरण',
    my_products: 'माझी उत्पादने',
    settlement: 'पैसे जमा (Settlement)',
    logout: 'लॉगआउट',
    start_selling: 'पिकांची विक्री सुरू करा',

    // Top Bar
    voice: 'व्हॉइस सहाय्यक',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    location_grid: 'बारामती क्लस्टर, पुणे | थेट एपीएमसी ग्रिड: पुणे क्लस्टर',
    national_portal: 'राष्ट्रीय कृषी पोर्टल (थेट)',

    // Greetings & Headers
    greeting: 'नमस्कार',
    online_status_line: 'ऑनलाइन • रिअल-टाइम पुणे APMC कनेक्टेड • थेट बाजार भाव सुरू',
    offline_status_line: 'ऑफलाइन मोड • स्थानिक रांग सक्रिय • जतन केलेले बाजार भाव',
    current_farm_location: 'शेतकऱ्याचे चालू स्थान',
    accuracy_manual: 'अचूकता: मॅन्युअल (तालुका/जिल्हा)',
    change_location: 'स्थान बदला',

    // KPI Cards
    todays_best_net: 'आजचा सर्वोत्तम नफा दर',
    current_crop_grade: 'चालू पीक प्रत (Grade)',
    external_ai_estimate: 'एआय व्हिज्युअल प्रतवारी अंदाज',
    active_pool_progress: 'सक्रिय पूल प्रगती',
    pending_payment: 'प्रलंबित रक्कम',
    released_in_nodal: 'नोडल खात्यातून हस्तांतरित',

    // Map & Journey
    mandi_map_title: 'शेत व जवळील बाजार समित्यांचा नकाशा',
    mandi_map_subtitle: 'बारामती क्लस्टर, पुणे येथून थेट मार्ग आणि प्रवासाचा वेळ',
    mandis_found: '२२ बाजार समित्या उपलब्ध',
    journey_title: 'थेट शेतकरी ते खरेदीदार बाजार जोडणी प्रवास',
    step1: '१. पिकांचे ३ फोटो घ्या',
    step2: '२. एआय प्रतवारी (Grade)',
    step3: '३. निव्वळ बाजार भाव तुलना',
    step4: '४. एफपीओ गट संकलन',
    step5: '५. बँक खात्यात थेट पैसे',

    recent_lots: 'नुकतीच नोंदवलेली पिके',
    recent_lots_subtitle: 'तुमच्या सक्रिय आणि पडताळणी झालेल्या पिकांची यादी',
    your_harvest_produce_lots: 'तुमचे काढणी केलेले पिकांचे लॉट्स',
    your_harvest_produce_lots_desc: 'तुमचे सक्रिय, प्रतवारी प्रमाणित व तपासणी केलेले पिकांचे लॉट्स',
    nearby_mandis: 'जवळील बाजार समित्या',
    near_baramati: 'बारामती क्लस्टर जवळ',
    direct_buyer_offers: 'खरेदीदारांच्या थेट ऑफर्स',
    direct_buyer_offers_subtitle: 'नोंदणीकृत खरेदीदारांकडून थेट खरेदीच्या ऑफर्स.',
    buyer_procurement: 'खरेदीदार खरेदी मागण्या',
    buyer_procurement_subtitle: 'अधिकृत बाजार समिती दराने थेट खरेदी करणाऱ्या नामांकित कंपन्यांच्या मागण्या. शून्य दलाली व थेट बँक जमा.',
    your_harvest_listings: 'तुमच्या उत्पादनांची संपूर्ण यादी',

    // Offline Banner
    offline_banner_title: 'तुम्ही सध्या ऑफलाइन आहात. पिकांचे मसुदे आणि पूलिंग विनंत्या तुमच्या ब्राउझरमध्ये सुरक्षितपणे जतन केल्या आहेत आणि इंटरनेट सुरू होताच आपोआप सिंक होतील.',
    offline_mode_badge: 'ऑफलाइन मोड',
    offline_mode_desc: 'स्थानिक स्टोरेज रांग सुरू आहे. तुम्ही पिके नोंदवू शकता आणि पूलिंग करू शकता; इंटरनेट सुरू झाल्यावर सिंक होईल.',
    offline_bullet_1: 'शेवटचे जतन केलेले स्थान: बारामती क्लस्टर, पुणे',
    offline_bullet_2: 'कॅश केलेले कृषी उत्पन्न बाजार भाव उपलब्ध',
    offline_bullet_3: 'थेट खरेदीदारांच्या ऑफर्स व पेमेंट परत ऑनलाइन होईपर्यंत थांबवले आहेत',

    // AI Assistant
    ai_assistant_title: 'कृषी-सेतू एआय सहाय्यक',
    ai_welcome: 'नमस्कार! मी तुमचा कृषी-सेतू एआय सहाय्यक आहे. मला जवळील बाजार भाव, वाहतूक खर्च वजा जाता निव्वळ नफा, गुणवत्ता प्रतवारी किंवा FPO पूलिंगबद्दल विचारा.',
    ai_input_placeholder: 'तुमचा प्रश्न टाइप करा किंवा बोला...',
    ask_tomato: 'माझ्या जवळ टोमॅटोचा आजचा भाव काय आहे?',
    ask_net: 'कोणत्या बाजारपेठेत मला सर्वाधिक निव्वळ नफा मिळेल?',
    ask_fpo: 'एफपीओ पूलिंग कसे काम करते?',
    ask_offline: 'ऑफलाइन मोडमध्ये डेटा कसा सिंक होतो?',

    // Buyer Navigation & Subpages (Marathi)
    buyer_nav_marketplace: 'बाजारपेठ (Marketplace)',
    buyer_nav_offers: 'माझ्या ऑफर्स (My Offers)',
    buyer_nav_delivery: 'डिलिव्हरी स्वीकृती (Delivery)',
    buyer_nav_trades: 'व्यवहार व सेटलमेंट (Trades)',

    // FPO Navigation (Marathi)
    fpo_nav_dashboard: 'डॅशबोर्ड',
    fpo_nav_verify: 'लॉट पडताळणी',
    fpo_nav_pools: 'पूल व्यवस्थापन',
    fpo_nav_logistics: 'लॉजिस्टिक्स',
    fpo_nav_buyers: 'खरेदीदार',
    switch_portal: 'पोर्टल बदला',

    // Buyer Marketplace (Marathi)
    b2b_marketplace_title: 'बी2बी घाऊक कृषी बाजार',
    b2b_marketplace_subtitle: 'एफपीओ-सत्यापित, एस्क्रो-संरक्षित एकत्रित कन्साइनमेंट. थेट शेतांशी जोडलेले.',
    rbi_compliant_escrow: 'RBI-अनुपालित एस्क्रो',
    available_pools: 'उपलब्ध पूल',
    total_stock: 'एकूण माल',
    total_market_value: 'एकूण बाजार मूल्य',
    registered_buyers: 'नोंदणीकृत खरेदीदार',
    direct_farmer_lots: 'थेट शेतकरी लॉट्स',
    aggregated_fpo_pools: 'एकत्रित एफपीओ पूल',
    filter_label: 'फिल्टर:',
    clear_filter: 'साफ करा',
    view_product_details: 'उत्पादन तपशील पहा',
    reserve_pool: 'पूल राखीव करा',
    already_reserved: 'आधीच राखीव',
    fpo_inspected: 'एफपीओ तपासणी केलेले',
    fpo_certified: 'एफपीओ प्रमाणित',
    available_volume: 'उपलब्ध प्रमाण',
    asking_rate: 'मागणी दर',
    producer_label: 'उत्पादक:',
    ai_quality_score: 'एआय गुणवत्ता स्कोर:',
    lot_id: 'लॉट क्र:',
    pool_fill_progress: 'पूल भरण्याची प्रगती',
    freight_saved: 'वाहतूक बचत',
    est_total_value: 'एकूण अंदाजित मूल्य:',
    auth_escrow_title: 'नोडल एस्क्रो निधी अधिकृत करा',
    zero_advance_protection: 'शून्य-अ‍ॅडव्हान्स एस्क्रो सुरक्षा',
    confirm_reserve: 'निश्चित करा व राखीव करा',
    cancel: 'रद्द करा',

    // Buyer Orders & RFQs (Marathi)
    procurement_orders_title: 'खरेदी मागण्या आणि RFQs',
    procurement_orders_subtitle: 'एफपीओकडे थेट खरेदी मागण्या प्रसिद्ध करा किंवा अस्तित्वातील करारांचा मागोवा घ्या.',
    broadcast_new_rfq: '+ नवीन RFQ पाठवा',
    target_ceiling_price: 'कमाल खरेदी दर',
    quality_tolerance: 'गुणवत्ता निकष',
    total_procurement_commitment: 'एकूण खरेदी रक्कम',
    delivery_destination: 'डिलिव्हरी ठिकाण',
    fulfillment_progress: 'पूर्तता प्रगती',
    contributing_farmers: 'सहभागी शेतकरी',
    fully_fulfilled: 'पूर्ण भरले ✓',
    remaining: 'उर्वरित',
    min_supply_lot: 'किमान पुरवठा लॉट',
    delivery_deadline: 'डिलिव्हरी अंतिम मुदत',

    // Buyer Delivery (Marathi)
    delivery_acceptance_title: 'डिलिव्हरी स्वीकृती व पेमेंट वितरण',
    delivery_acceptance_subtitle: 'डिजिटल वजन पावतीनुसार मालाची तपासणी करा. २४ तासांत निधी वितरित करा किंवा गुणवत्ता तक्रार नोंदवा.',
    no_active_deliveries: 'आपल्याकडे सध्या कोणतीही सक्रिय डिलिव्हरी नाही. प्रथम B2B बाजारपेठेत पूल राखीव करा.',
    consignment: 'कन्साइनमेंट',
    consignment_value: 'कन्साइनमेंट मूल्य:',
    assigned_fpo: 'नेमलेली एफपीओ',
    verified_bulk_weight: 'सत्यापित वजन',
    assigned_transporter: 'वाहतूकदार वाहन',
    contract_price: 'करार दर',
    ondc_ready_logistics: 'ONDC प्रोटोकॉल लॉजिस्टिक्स',
    vehicle_arrival_inspection: 'वाहन आगमन व गुणवत्ता तपासणी',
    vehicle_arrival_desc: 'वाहनाचा गेट क्यूआर पास स्कॅन करा आणि नोडल एस्क्रो पेमेंट जारी करण्यापूर्वी एफपीओ डिजिटल वजन पावतीशी क्रेट्सची जुळणी करा.',
    raise_dispute: 'गुणवत्ता/वजन तक्रार नोंदवा',
    confirm_delivery: 'डिलिव्हरी स्वीकारा व पैसे जमा करा',
    delivery_accepted_payout: 'डिलिव्हरी स्वीकारली व पेमेंट वितरित केले',
    dispute_raised_funds_held: 'तक्रार नोंदवली — निधी नोडल होल्डवर',
    my_procurement_bids: 'माझ्या थेट खरेदी बोली (FPO Linkage)',
    withdraw_bid: 'बोली मागे घ्या',

    // Buyer Trades (Marathi)
    trades_title: 'लिलाव व्यवहार आणि पूर्तता',
    trades_subtitle: 'डबल-ऑक्शन क्लिअरिंग व्यवहार, नोडल एस्क्रो लॉक्स, क्लिअरिंग व्हाउचर आणि त्वरित बँक UTR सेटलमेंट.',
    cleared_volume: 'क्लिअर झालेले प्रमाण',
    total_settled: 'एकूण सेटलमेंट',
    pending_escrow: 'प्रलंबित एस्क्रो',
    clearing_ledger: 'लिलाव क्लिअरिंग लेजर आणि व्हाउचर',
    pay_and_settle: 'पैसे भरा व सेटल करा',
    settled_badge: 'पूर्ण झाले ✓',

    // FPO Portal Translations (Marathi)
    fpo_registered_badge: 'नोंदणीकृत एफपीओ',
    fpo_lots_pending_btn: 'लॉट्स प्रलंबित',
    fpo_verify_lots_btn: 'पडताळणी केंद्र',
    fpo_kpi_pending: 'प्रलंबित',
    fpo_kpi_pending_sub: 'लॉट पडताळणी बाकी',
    fpo_kpi_verified: 'सत्यापित',
    fpo_kpi_verified_sub: 'तयार / पूलमध्ये',
    fpo_kpi_active_pools: 'सक्रिय पूल',
    fpo_kpi_active_pools_sub: 'सरासरी भरलेले',
    fpo_kpi_settled: 'सेटलमेंट',
    fpo_kpi_settled_sub: 'एकूण एस्क्रो मुक्त',
    fpo_tab_overview: 'आढावा',
    fpo_tab_lots: 'लॉट्स',
    fpo_tab_pools: 'पूल्स',
    fpo_tab_logistics: 'लॉजिस्टिक्स',
    fpo_hub_map_title: 'एफपीओ केंद्र व जवळील बाजार नकाशा',
    fpo_hub_map_sub: 'बारामती, पुणे — थेट एपीएमसी उपग्रह ग्रिड',
    fpo_lots_awaiting_title: 'पडताळणी प्रलंबित लॉट्स',
    fpo_view_all: 'सर्व पहा',
    fpo_review_btn: 'तपासा',
    fpo_active_pools_title: 'सक्रिय वाहतूक पूल्स',
    fpo_filled_pct: 'भरलेले',
    fpo_nearest_mandis_title: 'जवळील कृषी उत्पन्न बाजार समित्या',
    fpo_all_produce_lots: 'सर्व शेतकऱ्यांचे पीक लॉट्स',
    fpo_all_produce_lots_sub: 'शेतकऱ्यांच्या पिकांची तपासणी करा, डिजिटल वजन पावती द्या किंवा वाहतूक पूलमध्ये जोडा.',
    fpo_weigh_slip_queue_btn: 'वजन पावती रांग →',
    fpo_awaiting_inspection: 'तपासणी प्रतीक्षेत',
    fpo_inspect_btn: 'तपासा',
    fpo_active_regional_pools: 'सक्रिय विभागीय वाहतूक पूल्स',
    fpo_create_manage_pools: '+ नवीन पूल तयार करा / व्यवस्थापित करा',
    fpo_shared_freight_saved: 'सामायिक वाहतूक बचत',
    fpo_manage_btn: 'व्यवस्थापन करा →',
    fpo_logistics_schedule_title: 'लॉजिस्टिक्स आणि वाहतूक वेळापत्रक',
    fpo_logistics_schedule_sub: 'अनेक ठिकाणांवरून माल संकलन व वजन पावती वितरण.',
    fpo_route_optimizer_btn: 'मार्ग ऑप्टिमायझर उघडा →',
    fpo_assigned_fleet: 'नेमलेली वाहतूक वाहने',
    fpo_current_loop: 'चालू संकलन फेरी',
    fpo_full_utilization: 'पूर्ण वाहन वापर',
    fpo_collective_fuel_savings: 'एकत्रित इंधन बचत',
    fpo_cost_reduction: 'वाहतूक खर्च बचत',
    fpo_value_chain_title: 'एफपीओ मूल्य साखळी: शेतकरी → बाजार → पेमेंट',
    fpo_step_lot_collection: 'लॉट संकलन',
    fpo_step_ai_verification: 'AI गुणवत्ता पडताळणी',
    fpo_step_pool_aggregation: 'पूल एकत्रीकरण',
    fpo_step_apmc_buyer: 'APMC / खरेदीदार',
    fpo_step_escrow_settlement: 'एस्क्रो सेटलमेंट',

    // FPO Physical Verification (Marathi)
    fpo_verify_page_title: 'प्रत्यक्ष लॉट पडताळणी व वजन पावती',
    fpo_verify_page_sub: 'शेतकऱ्यांनी सादर केलेल्या एआय अंदाजाचे पुनरावलोकन करा, प्रमाणित वजन नोंदवा आणि पूलिंग पात्रता निश्चित करा.',
    fpo_dual_grade_rule: 'दुहेरी-प्रतवारी जबाबदारी नियम: जर शेतकऱ्याने एफपीओ प्रतवारीवर आक्षेप घेतला, तर तृतीय-पक्ष एपीएमसी प्रयोगशाळा फेरतपासणी करते. १००% पारदर्शक ऑडिट नोंदी.',
    fpo_awaiting_table_title: 'प्रत्यक्ष पडताळणीसाठी प्रलंबित लॉट्स',
    fpo_hub_queue_sub: 'बारामती एफपीओ केंद्र #१ आगमन रांग',
    fpo_col_farmer: 'शेतकरी',
    fpo_col_village: 'गाव',
    fpo_col_crop: 'पीक / वाण',
    fpo_col_ai_grade: 'दावा केलेली AI प्रत (Grade)',
    fpo_col_moisture: 'ओलावा (%)',
    fpo_col_status: 'स्थिती',
    fpo_col_action: 'कृती',
    fpo_inspect_weigh_btn: 'तपासा आणि वजन करा',
    fpo_modal_inspect_title: 'प्रत्यक्ष तपासणी व प्रमाणित वजन',
    fpo_modal_lot_id: 'लॉट क्र.',
    fpo_modal_farmer_name: 'शेतकऱ्याचे नाव',
    fpo_modal_crop_variety: 'पीक / वाण',
    fpo_modal_certified_weight: 'प्रमाणित वे-ब्रिज निव्वळ वजन (किलो)',
    fpo_modal_physical_grade: 'प्रत्यक्ष गुणवत्ता प्रतवारी (Grade)',
    fpo_modal_grade_a: 'प्रत अ (Grade A) — उच्च दर्जाची सुपरमार्केट व निर्यात गुणवत्ता',
    fpo_modal_grade_b: 'प्रत ब (Grade B) — प्रमाणित एपीएमसी बाजार समिती गुणवत्ता',
    fpo_modal_grade_c: 'प्रत क (Grade C) — प्रक्रिया उद्योग व स्थानिक वापर',
    fpo_modal_moisture_reading: 'डिजिटल ओलावा प्रमाण (%)',
    fpo_modal_inspector_notes: 'निरीक्षकाची टिप्पणी व गुणवत्ता नोंदी',
    fpo_modal_reject_btn: 'नाकारा व शेतकऱ्याला परत पाठवा',
    fpo_modal_confirm_btn: 'पुष्टी करा व वजन पावती द्या',

    // FPO Pool Management (Marathi)
    fpo_pools_page_title: 'वाहतूक पूल व्यवस्थापन',
    fpo_pools_page_sub: 'शेतकऱ्यांचे माल एकत्र करून ट्रक लोड तयार करा, ज्यामुळे वाहतूक खर्चात ३५% पर्यंत बचत होते.',
    fpo_create_pool_btn: '+ नवीन बॅच पूल सुरू करा',
    fpo_target_capacity: 'लक्ष्य क्षमता',
    fpo_current_volume: 'सध्याचे वजन',
    fpo_target_price: 'अपेक्षित दर',
    fpo_allowed_grades: 'स्वीकृत प्रतवारी',
    fpo_closes_in: 'बंद होण्याची वेळ',
    fpo_optimize_route_btn: 'वाहतूक मार्ग ऑप्टिमाइझ करा',
    fpo_lock_pool_btn: 'पूल लॉक करा व पाठवा',
    fpo_pool_locked_badge: 'पूल लॉक केला आणि पाठवला',
    fpo_contributing_farmers: 'सहभागी शेतकरी',
    fpo_modal_create_pool_title: 'नवीन विभागीय बॅच पूल सुरू करा',
    fpo_modal_crop_name: 'पिकाचे नाव',
    fpo_modal_variety: 'वाण / प्रकार',
    fpo_modal_target_weight_kg: 'लक्ष्य बॅच वजन (किलो)',
    fpo_modal_target_price_qtl: 'लक्ष्य बाजार भाव (₹/क्विंटल)',
    fpo_modal_dest_mandi: 'गंतव्य बाजार / खरेदीदार केंद्र',
    fpo_modal_collection_hub: 'एफपीओ संकलन केंद्र',
    fpo_modal_cutoff_hrs: 'पूल बंद होण्याची मुदत (तास)',
    fpo_modal_launch_btn: 'पूल सुरू करा',

    // FPO Logistics (Marathi)
    fpo_logistics_page_title: 'लॉजिस्टिक्स आणि मार्ग ऑप्टिमायझेशन',
    fpo_logistics_page_sub: 'Google OR-Tools CVRPTW अल्गोरिदमद्वारे शेतकऱ्यांकडून माल संकलनाचा सर्वोत्तम मार्ग आणि वाहतूक व्यवस्थापन.',
    fpo_cost_reduction_badge: 'वैयक्तिक वाहनांच्या तुलनेत २८.५% वाहतूक बचत',
    fpo_optimized_sequence: 'ऑप्टिमाइझ केलेला बहु-थांबा संकलन क्रम',
    fpo_cvrptw_algo_sub: 'अल्गोरिदम: कॅपेसिटेटेड व्हेईकल राउटिंग विथ टाइम विंडोज (CVRPTW)',
    fpo_vehicle_label: 'वाहन',
    fpo_total_loop_dist: 'एकूण फेरी अंतर',
    fpo_driver_assigned: 'नेमलेला चालक',
    fpo_est_route_cost: 'अंदाजित मार्ग खर्च',
    fpo_farmer_savings: 'शेतकऱ्यांची एकत्रित बचत',
    fpo_scheduled_stops_title: 'नियोजित संकलन वेळापत्रक आणि थांबे',
    fpo_stop_label: 'थांबा',
    fpo_farmer_contact: 'शेतकरी संपर्क',
    fpo_pickup_weight: 'संकलन वजन',
    fpo_dispatch_btn: 'बहु-थांबा वाहतूक अधिकृत करा व ट्रॅन्झिट पावती द्या',
    fpo_dispatched_badge: 'वाहतुकीत मार्गस्थ',

    // FPO Verified Buyers (Marathi)
    fpo_buyers_page_title: 'सत्यापित B2B खरेदीदार निर्देशिका',
    fpo_buyers_page_sub: 'नोंदणीकृत संस्थात्मक खरेदीदार, अन्न किरकोळ विक्रेते आणि प्रक्रिया उद्योग ज्यांचे पेमेंट रेकॉर्ड सत्यापित आहे.',
    fpo_buyers_kyc_badge: 'सर्व खरेदीदार केवायसी व जीएसटीआयएन प्रमाणित',
    fpo_reliability_score: 'विश्वसनीयता स्कोअर',
    fpo_gstin_label: 'GSTIN',
    fpo_quality_req_label: 'गुणवत्ता निकष',
    fpo_payment_term_label: 'पेमेंट सेटलमेंट अटी',
    fpo_target_commodities: 'प्रमुख खरेदी पिके',
    fpo_historical_vol: 'सत्यापित ऐतिहासिक खरेदी प्रमाण',
    fpo_contact_procurement_btn: 'खरेदी विभागाशी संपर्क साधा',
    fpo_send_pool_offer_btn: 'पूल ऑफर पाठवा',
    auction_listing: 'लिलाव यादी',
    live_apmc_grid: 'थेट एपीएमसी ग्रिड: पुणे क्लस्टर',
  },

  hi: {
    // Navigation
    dashboard: 'डैशबोर्ड',
    grade_crop: 'फसल ग्रेडिंग',
    market_prices: 'मंडी भाव',
    sale_advisor: 'बिक्री सलाहकार',
    pooling: 'एफपीओ समूह पूलिंग',
    my_products: 'मेरे उत्पाद',
    settlement: 'भुगतान विवरण',
    logout: 'लॉगआउट',
    start_selling: 'फसल बेचना शुरू करें',

    // Top Bar
    voice: 'वॉयस सहायक',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    location_grid: 'बारामती क्लस्टर, पुणे | लाइव एपीएमसी ग्रिड: पुणे क्लस्टर',
    national_portal: 'राष्ट्रीय कृषि पोर्टल (लाइव)',

    // Greetings & Headers
    greeting: 'नमस्ते',
    online_status_line: 'ऑनलाइन • रियल-टाइम पुणे APMC कनेक्टेड • लाइव मार्केट फीड सक्रिय',
    offline_status_line: 'ऑफलाइन मोड • स्थानीय कतार सक्रिय • सहेजे गए मंडी भाव',
    current_farm_location: 'किसान का वर्तमान स्थान',
    accuracy_manual: 'सटीकता: मैन्युअल (तालुका/ज़िला)',
    change_location: 'स्थान बदलें',

    // KPI Cards
    todays_best_net: 'आज का सर्वोत्तम शुद्ध लाभ',
    current_crop_grade: 'वर्तमान फसल ग्रेड',
    external_ai_estimate: 'एआई विजुअल ग्रेडिंग अनुमान',
    active_pool_progress: 'सक्रिय पूल प्रगति',
    pending_payment: 'लंबित भुगतान',
    released_in_nodal: 'नोडल खाते में स्वीकृत',

    // Map & Journey
    mandi_map_title: 'खेत और निकटतम मंडी नक्शा',
    mandi_map_subtitle: 'बारामती क्लस्टर, पुणे से लाइव मार्ग और यात्रा समय',
    mandis_found: '२२ मंडियां उपलब्ध',
    journey_title: 'संपूर्ण कृषि बाजार संपर्क यात्रा',
    step1: '१. फसल के ३ फोटो लें',
    step2: '२. एआई गुणवत्ता ग्रेडिंग',
    step3: '३. शुद्ध मंडी भाव तुलना',
    step4: '४. एफपीओ समूह पूलिंग',
    step5: '५. बैंक खाते में सीधा भुगतान',

    recent_lots: 'हाल की फसलें',
    recent_lots_subtitle: 'प्रणाली में आपकी सक्रिय और सत्यापित फसलें',
    your_harvest_produce_lots: 'आपकी उपज के पंजीकृत लॉट्स',
    your_harvest_produce_lots_desc: 'आपके सक्रिय, श्रेणीबद्ध और प्रमाणित फसल लॉट्स',
    nearby_mandis: 'निकटतम मंडियां',
    near_baramati: 'बारामती क्लस्टर के पास',
    direct_buyer_offers: 'खरीदारों के सीधे ऑफर्स',
    direct_buyer_offers_subtitle: 'पंजीकृत खरीदारों से सीधी फसल खरीद के प्रस्ताव।',
    buyer_procurement: 'खरीदार खरीद मांग',
    buyer_procurement_subtitle: 'आधिकारिक मंडी भाव पर सीधे खरीद करने वाली कंपनियों की मांगें। शून्य कमीशन और सीधा बैंक भुगतान।',
    your_harvest_listings: 'आपकी फसलों की सूची',

    // Offline Banner
    offline_banner_title: 'आप ऑफलाइन हैं। फसल ड्राफ्ट और पूल अनुरोध आपके स्थानीय ब्राउज़र में सुरक्षित रूप से कतारबद्ध हैं और ऑनलाइन आने पर स्वचालित रूप से सिंक हो जाएंगे।',
    offline_mode_badge: 'ऑफलाइन मोड',
    offline_mode_desc: 'सिम्युलेटेड लोकल स्टोरेज कतार सक्रिय है। आप फसल जोड़ सकते हैं और पूल में शामिल हो सकते हैं; इंटरनेट जुड़ने पर सिंक हो जाएंगे।',
    offline_bullet_1: 'अंतिम सहेजा गया स्थान: बारामती क्लस्टर, पुणे',
    offline_bullet_2: 'कैश्ड मंडी भाव उपलब्ध हैं',
    offline_bullet_3: 'लाइव खरीदार ऑफर और भुगतान ऑनलाइन होने तक स्थगित रहेंगे',

    // AI Assistant
    ai_assistant_title: 'कृषि-सेतु एआई सहायक',
    ai_welcome: 'नमस्ते! मैं आपका कृषि-सेतु एआई सहायक हूँ। मुझसे निकटतम मंडी भाव, परिवहन लागत घटाकर शुद्ध मुनाफा, गुणवत्ता ग्रेडिंग या FPO पूलिंग के बारे में पूछें।',
    ai_input_placeholder: 'अपना प्रश्न टाइप करें या बोलें...',
    ask_tomato: 'मेरे पास आज टमाटर का भाव क्या है?',
    ask_net: 'कौन सी मंडी मुझे सबसे ज्यादा शुद्ध मुनाफा देगी?',
    ask_fpo: 'एफपीओ पूलिंग कैसे काम करती है?',
    ask_offline: 'ऑफलाइन मोड में डेटा कैसे सुरक्षित रहता है?',

    // Buyer Navigation & Subpages (Hindi)
    buyer_nav_marketplace: 'मार्केटप्लेस (Marketplace)',
    buyer_nav_offers: 'मेरे ऑफर्स (My Offers)',
    buyer_nav_delivery: 'वितरण स्वीकृति (Delivery)',
    buyer_nav_trades: 'व्यापार व निपटान (Trades)',

    // FPO Navigation (Hindi)
    fpo_nav_dashboard: 'डैशबोर्ड',
    fpo_nav_verify: 'लॉट सत्यापन',
    fpo_nav_pools: 'पूल प्रबंधन',
    fpo_nav_logistics: 'लॉजिस्टिक्स',
    fpo_nav_buyers: 'खरीदार',
    switch_portal: 'पोर्टल बदलें',

    // Buyer Marketplace (Hindi)
    b2b_marketplace_title: 'बी2बी थोक कृषि मंडी',
    b2b_marketplace_subtitle: 'एफपीओ-सत्यापित, एस्क्रो-संरक्षित समूहीकृत खेप। सीधे खेतों से जुड़े हुए।',
    rbi_compliant_escrow: 'RBI-अनुरूप एस्क्रो',
    available_pools: 'उपलब्ध पूल',
    total_stock: 'कुल स्टॉक',
    total_market_value: 'कुल बाज़ार मूल्य',
    registered_buyers: 'पंजीकृत खरीदार',
    direct_farmer_lots: 'सीधे किसान लॉट',
    aggregated_fpo_pools: 'समूहीकृत एफपीओ पूल',
    filter_label: 'फ़िल्टर:',
    clear_filter: 'हटाएं',
    view_product_details: 'उत्पाद विवरण देखें',
    reserve_pool: 'पूल आरक्षित करें',
    already_reserved: 'पहले से आरक्षित',
    fpo_inspected: 'एफपीओ द्वारा जांचा गया',
    fpo_certified: 'एफपीओ प्रमाणित',
    available_volume: 'उपलब्ध मात्रा',
    asking_rate: 'मांग दर',
    producer_label: 'उत्पादक:',
    ai_quality_score: 'एआई गुणवत्ता स्कोर:',
    lot_id: 'लॉट आईडी:',
    pool_fill_progress: 'पूल भराव प्रगति',
    freight_saved: 'भाड़ा बचत',
    est_total_value: 'कुल अनुमानित मूल्य:',
    auth_escrow_title: 'नोडल एस्क्रो होल्ड अधिकृत करें',
    zero_advance_protection: 'शून्य-अग्रिम एस्क्रो सुरक्षा',
    confirm_reserve: 'पुष्टि करें और आरक्षित करें',
    cancel: 'रद्द करें',

    // Buyer Orders & RFQs (Hindi)
    procurement_orders_title: 'खरीद आदेश और आरएफक्यू',
    procurement_orders_subtitle: 'एफपीओ को प्रत्यक्ष खरीद आवश्यकताएं प्रकाशित करें या मौजूदा अनुबंधों को ट्रैक करें।',
    broadcast_new_rfq: '+ नया आरएफक्यू भेजें',
    target_ceiling_price: 'अधिकतम खरीद दर',
    quality_tolerance: 'गुणवत्ता सहनशीलता',
    total_procurement_commitment: 'कुल खरीद प्रतिबद्धता',
    delivery_destination: 'वितरण गंतव्य',
    fulfillment_progress: 'पूर्ति प्रगति',
    contributing_farmers: 'योगदानकर्ता किसान',
    fully_fulfilled: 'पूरी तरह संपन्न ✓',
    remaining: 'शेष',
    min_supply_lot: 'न्यूनतम आपूर्ति लॉट',
    delivery_deadline: 'वितरण अंतिम तिथि',

    // Buyer Delivery (Hindi)
    delivery_acceptance_title: 'वितरण स्वीकृति और भुगतान जारी',
    delivery_acceptance_subtitle: 'डिजिटल वजन पर्ची के अनुसार माल का निरीक्षण करें। 24 घंटे में भुगतान जारी करें या गुणवत्ता समायोजन दर्ज करें।',
    no_active_deliveries: 'आपके पास कोई सक्रिय वितरण नहीं है। पहले बी2बी मार्केटप्लेस में पूल आरक्षित करें।',
    consignment: 'कंसाइनमेंट',
    consignment_value: 'कंसाइनमेंट मूल्य:',
    assigned_fpo: 'नियुक्त एफपीओ',
    verified_bulk_weight: 'सत्यापित वजन',
    assigned_transporter: 'ट्रांसपोर्टर वाहन',
    contract_price: 'अनुबंध दर',
    ondc_ready_logistics: 'ओएनडीसी प्रोटोकॉल लॉजिस्टिक्स',
    vehicle_arrival_inspection: 'वाहन आगमन एवं गुणवत्ता निरीक्षण',
    vehicle_arrival_desc: 'वाहन का गेट क्यूआर पास स्कैन करें और नोडल एस्क्रो भुगतान जारी करने से पहले एफपीओ डिजिटल वजन पर्ची से क्रेट का मिलान करें।',
    raise_dispute: 'गुणवत्ता/वजन विवाद दर्ज करें',
    confirm_delivery: 'वितरण स्वीकारें और भुगतान जारी करें',
    delivery_accepted_payout: 'वितरण स्वीकृत और भुगतान जारी',
    dispute_raised_funds_held: 'विवाद दर्ज — धनराशि नोडल होल्ड पर',
    my_procurement_bids: 'मेरी प्रत्यक्ष खरीद बोलियां (FPO Linkage)',
    withdraw_bid: 'बोली वापस लें',

    // Buyer Trades (Hindi)
    trades_title: 'नीलामी व्यापार और निपटान',
    trades_subtitle: 'डबल-नीलामी संपन्न अनुबंध, नोडल एस्क्रो लॉक, क्लीयरिंग वाउचर और तत्काल बैंक यूटीआर निपटान।',
    cleared_volume: 'क्लीयर मात्रा',
    total_settled: 'कुल निपटान',
    pending_escrow: 'लंबित एस्क्रो',
    clearing_ledger: 'नीलामी क्लीयरिंग बहीखाता और वाउचर',
    pay_and_settle: 'भुगतान करें और निपटाएं',
    settled_badge: 'निपटारा संपन्न ✓',

    // FPO Portal Translations (Hindi)
    fpo_registered_badge: 'पंजीकृत एफपीओ',
    fpo_lots_pending_btn: 'लॉट्स लंबित',
    fpo_verify_lots_btn: 'सत्यापन केंद्र',
    fpo_kpi_pending: 'लंबित',
    fpo_kpi_pending_sub: 'लॉट सत्यापन बाकी',
    fpo_kpi_verified: 'सत्यापित',
    fpo_kpi_verified_sub: 'तैयार / पूल में',
    fpo_kpi_active_pools: 'सक्रिय पूल',
    fpo_kpi_active_pools_sub: 'औसत भरा हुआ',
    fpo_kpi_settled: 'सेटलमेंट',
    fpo_kpi_settled_sub: 'कुल एस्क्रो विमोचित',
    fpo_tab_overview: 'अवलोकन',
    fpo_tab_lots: 'लॉट्स',
    fpo_tab_pools: 'पूल्स',
    fpo_tab_logistics: 'लॉजिस्टिक्स',
    fpo_hub_map_title: 'एफपीओ केंद्र व निकटवर्ती मंडी मानचित्र',
    fpo_hub_map_sub: 'बारामती, पुणे — लाइव एपीएमसी सैटेलाइट ग्रिड',
    fpo_lots_awaiting_title: 'सत्यापन प्रतीक्षारत लॉट्स',
    fpo_view_all: 'सभी देखें',
    fpo_review_btn: 'जांचें',
    fpo_active_pools_title: 'सक्रिय परिवहन पूल्स',
    fpo_filled_pct: 'भरा हुआ',
    fpo_nearest_mandis_title: 'निकटतम एपीएमसी मंडियां',
    fpo_all_produce_lots: 'सभी किसानों के फसल लॉट्स',
    fpo_all_produce_lots_sub: 'किसानों की फसलों की जांच करें, डिजिटल वजन पर्ची दें या परिवहन पूल में जोड़ें।',
    fpo_weigh_slip_queue_btn: 'वजन पर्ची कतार →',
    fpo_awaiting_inspection: 'निरीक्षण प्रतीक्षारत',
    fpo_inspect_btn: 'जांचें',
    fpo_active_regional_pools: 'सक्रिय क्षेत्रीय परिवहन पूल',
    fpo_create_manage_pools: '+ नया पूल बनाएं / प्रबंधित करें',
    fpo_shared_freight_saved: 'साझा परिवहन बचत',
    fpo_manage_btn: 'प्रबंधित करें →',
    fpo_logistics_schedule_title: 'लॉजिस्टिक्स और परिवहन समय सारिणी',
    fpo_logistics_schedule_sub: 'बहु-स्थान संग्रह मार्ग और वजन पर्ची प्रेषण।',
    fpo_route_optimizer_btn: 'रूट ऑप्टिमाइज़र खोलें →',
    fpo_assigned_fleet: 'नियुक्त वाहन बेड़ा',
    fpo_current_loop: 'वर्तमान संग्रह फेरा',
    fpo_full_utilization: 'पूर्ण वाहन उपयोग',
    fpo_collective_fuel_savings: 'सामूहिक ईंधन बचत',
    fpo_cost_reduction: 'लागत में कमी',
    fpo_value_chain_title: 'एफपीओ मूल्य श्रृंखला: किसान → मंडी → भुगतान',
    fpo_step_lot_collection: 'लॉट संग्रह',
    fpo_step_ai_verification: 'AI गुणवत्ता सत्यापन',
    fpo_step_pool_aggregation: 'पूल एकत्रीकरण',
    fpo_step_apmc_buyer: 'APMC / खरीदार',
    fpo_step_escrow_settlement: 'एस्क्रो सेटलमेंट',

    // FPO Physical Verification (Hindi)
    fpo_verify_page_title: 'भौतिक लॉट सत्यापन व वजन पर्ची',
    fpo_verify_page_sub: 'किसान द्वारा प्रस्तुत एआई अनुमान की समीक्षा करें, प्रमाणित वजन दर्ज करें और पूलिंग पात्रता तय करें।',
    fpo_dual_grade_rule: 'दोहरी-ग्रेड जवाबदेही नियम: यदि किसान एफपीओ ग्रेडिंग पर आपत्ति करता है, तो तृतीय-पक्ष एपीएमसी प्रयोगशाला पुनः परीक्षण करती है। १००% पारदर्शी ऑडिट ट्रेल।',
    fpo_awaiting_table_title: 'भौतिक सत्यापन प्रतीक्षारत लॉट्स',
    fpo_hub_queue_sub: 'बारामती एफपीओ हब #१ आगमन कतार',
    fpo_col_farmer: 'किसान',
    fpo_col_village: 'गांव',
    fpo_col_crop: 'फसल / किस्म',
    fpo_col_ai_grade: 'दावा किया गया AI ग्रेड',
    fpo_col_moisture: 'नमी (%)',
    fpo_col_status: 'स्थिति',
    fpo_col_action: 'कार्रवाई',
    fpo_inspect_weigh_btn: 'जांचें और वजन करें',
    fpo_modal_inspect_title: 'भौतिक निरीक्षण और प्रमाणित वजन',
    fpo_modal_lot_id: 'लॉट आईडी',
    fpo_modal_farmer_name: 'किसान का नाम',
    fpo_modal_crop_variety: 'फसल / किस्म',
    fpo_modal_certified_weight: 'प्रमाणित वे-ब्रिज शुद्ध वजन (किलो)',
    fpo_modal_physical_grade: 'भौतिक ग्रेड आवंटन',
    fpo_modal_grade_a: 'ग्रेड ए — प्रीमियम सुपरमार्केट एवं निर्यात गुणवत्ता',
    fpo_modal_grade_b: 'ग्रेड बी — मानक एपीएमसी मंडी गुणवत्ता',
    fpo_modal_grade_c: 'ग्रेड सी — प्रसंस्करण उद्योग एवं स्थानीय उपयोग',
    fpo_modal_moisture_reading: 'डिजिटल नमी माप (%)',
    fpo_modal_inspector_notes: 'निरीक्षक अवलोकन एवं गुणवत्ता नोट्स',
    fpo_modal_reject_btn: 'अस्वीकार करें व किसान को लौटाएं',
    fpo_modal_confirm_btn: 'पुष्टि करें और वजन पर्ची जारी करें',

    // FPO Pool Management (Hindi)
    fpo_pools_page_title: 'परिवहन पूल प्रबंधन',
    fpo_pools_page_sub: 'किसानों की उपज को ट्रकलॉड लॉट में एकत्रित करें, जिससे परिवहन लागत में ३५% तक की बचत होती है।',
    fpo_create_pool_btn: '+ नया बैच पूल बनाएं',
    fpo_target_capacity: 'लक्ष्य क्षमता',
    fpo_current_volume: 'वर्तमान वजन',
    fpo_target_price: 'अपेक्षित दर',
    fpo_allowed_grades: 'स्वीकृत ग्रेड',
    fpo_closes_in: 'समाप्ति समय',
    fpo_optimize_route_btn: 'मार्ग अनुकूलित करें',
    fpo_lock_pool_btn: 'पूल लॉक करें व प्रेषित करें',
    fpo_pool_locked_badge: 'पूल लॉक व प्रेषित',
    fpo_contributing_farmers: 'योगदानकर्ता किसान',
    fpo_modal_create_pool_title: 'नया क्षेत्रीय बैच पूल प्रारंभ करें',
    fpo_modal_crop_name: 'फसल का नाम',
    fpo_modal_variety: 'किस्म / प्रकार',
    fpo_modal_target_weight_kg: 'लक्ष्य बैच वजन (किलो)',
    fpo_modal_target_price_qtl: 'लक्ष्य मंडी भाव (₹/क्विंटल)',
    fpo_modal_dest_mandi: 'गंतव्य मंडी / खरीदार केंद्र',
    fpo_modal_collection_hub: 'एफपीओ संग्रह केंद्र',
    fpo_modal_cutoff_hrs: 'पूल बंद होने की समय सीमा (घंटे)',
    fpo_modal_launch_btn: 'पूल शुरू करें',

    // FPO Logistics (Hindi)
    fpo_logistics_page_title: 'लॉजिस्टिक्स और मार्ग अनुकूलन',
    fpo_logistics_page_sub: 'Google OR-Tools CVRPTW एल्गोरिदम द्वारा किसानों से माल संग्रह का सर्वोत्तम मार्ग और परिवहन प्रबंधन।',
    fpo_cost_reduction_badge: 'एकल वाहनों की तुलना में २८.५% परिवहन बचत',
    fpo_optimized_sequence: 'अनुकूलित बहु-स्टॉप संग्रह क्रम',
    fpo_cvrptw_algo_sub: 'एल्गोरिदम: कैपेसिटेटेड व्हीकल रूटिंग विथ टाइम विंडोज (CVRPTW)',
    fpo_vehicle_label: 'वाहन',
    fpo_total_loop_dist: 'कुल फेरा दूरी',
    fpo_driver_assigned: 'नियुक्त चालक',
    fpo_est_route_cost: 'अनुमानित मार्ग लागत',
    fpo_farmer_savings: 'किसानों की सामूहिक बचत',
    fpo_scheduled_stops_title: 'निर्धारित संग्रह समय सारिणी और स्टॉप्स',
    fpo_stop_label: 'स्टॉप',
    fpo_farmer_contact: 'किसान संपर्क',
    fpo_pickup_weight: 'संग्रह वजन',
    fpo_dispatch_btn: 'बहु-स्टॉप प्रेषण अधिकृत करें और ट्रांजिट मैनिफेस्ट जारी करें',
    fpo_dispatched_badge: 'परिवहन में गतिशील',

    // FPO Verified Buyers (Hindi)
    fpo_buyers_page_title: 'सत्यापित B2B खरीदार निर्देशिका',
    fpo_buyers_page_sub: 'पंजीकृत संस्थागत खरीदार, खाद्य खुदरा विक्रेता और प्रसंस्करण इकाइयां जिनके भुगतान रिकॉर्ड सत्यापित हैं।',
    fpo_buyers_kyc_badge: 'सभी खरीदार केवाईसी और जीएसटी सत्यापित',
    fpo_reliability_score: 'विश्वसनीयता स्कोर',
    fpo_gstin_label: 'GSTIN',
    fpo_quality_req_label: 'गुणवत्ता आवश्यकताएं',
    fpo_payment_term_label: 'भुगतान निपटान शर्तें',
    fpo_target_commodities: 'प्रमुख खरीद फसलें',
    fpo_historical_vol: 'सत्यापित ऐतिहासिक खरीद मात्रा',
    fpo_contact_procurement_btn: 'खरीद डेस्क से संपर्क करें',
    fpo_send_pool_offer_btn: 'पूल ऑफर भेजें',
    auction_listing: 'नीलामी सूची',
    live_apmc_grid: 'लाइव एपीएमसी ग्रिड: पुणे क्लस्टर',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem('krishisetu_lang') || 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('krishisetu_lang', lang);
    } catch {}
  }, [lang]);

  const t = (key, fallback) => {
    const dict = translations[lang] || translations.en;
    return dict[key] || translations.en[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
